#
# Этот тест следует вызывать командой:
#
#   svs test_adap.ini
#
# Результат окажется в файле adap.trace.
#

# Перенаправляем вывод консоли в файл.
! rm -f adap.trace
set console log=adap.trace

# Включаем трассировку машинных команд, регистров и памяти.
set cpu0 trace

# Загружаем программу в память.
load adap.b6

# Запускаем программу.
d PC 30000
step 100000

quit
